internalName = "tech.niceeli.homebrew"
friendlyName = "PhysFormer 2"
version = "1.0.0"
introVid = "./intro.mp4"
gameMenuScene = "mainMenu"
TitleBackground = "./greenGrad.jpg"
compStartLevel = "Level1"
UGCApi = "http://homebrew.niceeli.tech/"
tags = ["platformer", "fun", "difficult"]